// <auto-generated />
using GroceryShopping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryShopping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroceryShopping.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh and delicious fruits",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fresh and healthy vegetables",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Milk and dairy products",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh bakery products",
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tasty snacks and packaged foods",
                            Name = "Snacks"
                        });
                });

            modelBuilder.Entity("GroceryShopping.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Fresh red apples",
                            ImageUrl = "/images/products/apples.jpg",
                            IsAvailable = true,
                            Name = "Fresh Apples",
                            Price = 180m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Fresh ripe bananas",
                            ImageUrl = "/images/products/bananas.jpg",
                            IsAvailable = true,
                            Name = "Fresh Bananas",
                            Price = 60m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Fresh potatoes",
                            ImageUrl = "/images/products/potatoes.jpg",
                            IsAvailable = true,
                            Name = "Potatoes",
                            Price = 40m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Full cream fresh milk",
                            ImageUrl = "/images/products/milk.jpg",
                            IsAvailable = true,
                            Name = "Fresh Milk",
                            Price = 60m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Healthy brown bread",
                            ImageUrl = "/images/products/bread.jpg",
                            IsAvailable = true,
                            Name = "Brown Bread",
                            Price = 50m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Crispy potato chips",
                            ImageUrl = "/images/products/chips.jpg",
                            IsAvailable = true,
                            Name = "Potato Chips",
                            Price = 30m,
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("GroceryShopping.Models.Product", b =>
                {
                    b.HasOne("GroceryShopping.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GroceryShopping.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
